//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosneuro
{
    [Serializable]
    public class NeuroDecoderMsg : Message
    {
        public const string k_RosMessageName = "rosneuro_msgs/NeuroDecoder";
        public override string RosMessageName => k_RosMessageName;

        public string type;
        public string path;
        public int[] classes;

        public NeuroDecoderMsg()
        {
            this.type = "";
            this.path = "";
            this.classes = new int[0];
        }

        public NeuroDecoderMsg(string type, string path, int[] classes)
        {
            this.type = type;
            this.path = path;
            this.classes = classes;
        }

        public static NeuroDecoderMsg Deserialize(MessageDeserializer deserializer) => new NeuroDecoderMsg(deserializer);

        private NeuroDecoderMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.type);
            deserializer.Read(out this.path);
            deserializer.Read(out this.classes, sizeof(int), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
            serializer.Write(this.path);
            serializer.WriteLength(this.classes);
            serializer.Write(this.classes);
        }

        public override string ToString()
        {
            return "NeuroDecoderMsg: " +
            "\ntype: " + type.ToString() +
            "\npath: " + path.ToString() +
            "\nclasses: " + System.String.Join(", ", classes.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
