//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Rosneuro
{
    [Serializable]
    public class NeuroOutputMsg : Message
    {
        public const string k_RosMessageName = "rosneuro_msgs/NeuroOutput";
        public override string RosMessageName => k_RosMessageName;

        //  NeuroOutput Message
        //  Header
        public HeaderMsg header;
        //  NeuroHeader
        public NeuroHeaderMsg neuroheader;
        //  Output
        public NeuroDataFloatMsg softpredict;
        public NeuroDataInt32Msg hardpredict;
        //  NeuroDecoder
        public NeuroDecoderMsg decoder;

        public NeuroOutputMsg()
        {
            this.header = new HeaderMsg();
            this.neuroheader = new NeuroHeaderMsg();
            this.softpredict = new NeuroDataFloatMsg();
            this.hardpredict = new NeuroDataInt32Msg();
            this.decoder = new NeuroDecoderMsg();
        }

        public NeuroOutputMsg(HeaderMsg header, NeuroHeaderMsg neuroheader, NeuroDataFloatMsg softpredict, NeuroDataInt32Msg hardpredict, NeuroDecoderMsg decoder)
        {
            this.header = header;
            this.neuroheader = neuroheader;
            this.softpredict = softpredict;
            this.hardpredict = hardpredict;
            this.decoder = decoder;
        }

        public static NeuroOutputMsg Deserialize(MessageDeserializer deserializer) => new NeuroOutputMsg(deserializer);

        private NeuroOutputMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.neuroheader = NeuroHeaderMsg.Deserialize(deserializer);
            this.softpredict = NeuroDataFloatMsg.Deserialize(deserializer);
            this.hardpredict = NeuroDataInt32Msg.Deserialize(deserializer);
            this.decoder = NeuroDecoderMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.neuroheader);
            serializer.Write(this.softpredict);
            serializer.Write(this.hardpredict);
            serializer.Write(this.decoder);
        }

        public override string ToString()
        {
            return "NeuroOutputMsg: " +
            "\nheader: " + header.ToString() +
            "\nneuroheader: " + neuroheader.ToString() +
            "\nsoftpredict: " + softpredict.ToString() +
            "\nhardpredict: " + hardpredict.ToString() +
            "\ndecoder: " + decoder.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
