//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosneuro
{
    [Serializable]
    public class NeuroDataFloatMsg : Message
    {
        public const string k_RosMessageName = "rosneuro_msgs/NeuroDataFloat";
        public override string RosMessageName => k_RosMessageName;

        public NeuroDataInfoMsg info;
        public float[] data;

        public NeuroDataFloatMsg()
        {
            this.info = new NeuroDataInfoMsg();
            this.data = new float[0];
        }

        public NeuroDataFloatMsg(NeuroDataInfoMsg info, float[] data)
        {
            this.info = info;
            this.data = data;
        }

        public static NeuroDataFloatMsg Deserialize(MessageDeserializer deserializer) => new NeuroDataFloatMsg(deserializer);

        private NeuroDataFloatMsg(MessageDeserializer deserializer)
        {
            this.info = NeuroDataInfoMsg.Deserialize(deserializer);
            deserializer.Read(out this.data, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.info);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "NeuroDataFloatMsg: " +
            "\ninfo: " + info.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
