//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosneuro
{
    [Serializable]
    public class NeuroHeaderMsg : Message
    {
        public const string k_RosMessageName = "rosneuro_msgs/NeuroHeader";
        public override string RosMessageName => k_RosMessageName;

        public uint seq;

        public NeuroHeaderMsg()
        {
            this.seq = 0;
        }

        public NeuroHeaderMsg(uint seq)
        {
            this.seq = seq;
        }

        public static NeuroHeaderMsg Deserialize(MessageDeserializer deserializer) => new NeuroHeaderMsg(deserializer);

        private NeuroHeaderMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.seq);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.seq);
        }

        public override string ToString()
        {
            return "NeuroHeaderMsg: " +
            "\nseq: " + seq.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
