//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosneuro
{
    [Serializable]
    public class NeuroDataInfoMsg : Message
    {
        public const string k_RosMessageName = "rosneuro_msgs/NeuroDataInfo";
        public override string RosMessageName => k_RosMessageName;

        //  NeuroDataInfo Message
        public ushort nsamples;
        public ushort nchannels;
        public ushort stride;
        public string unit;
        public string transducter;
        public string prefiltering;
        //  Hardware prefiltering
        public byte isint;
        public double[] minmax;
        public string[] labels;
        //  Labels of channels

        public NeuroDataInfoMsg()
        {
            this.nsamples = 0;
            this.nchannels = 0;
            this.stride = 0;
            this.unit = "";
            this.transducter = "";
            this.prefiltering = "";
            this.isint = 0;
            this.minmax = new double[0];
            this.labels = new string[0];
        }

        public NeuroDataInfoMsg(ushort nsamples, ushort nchannels, ushort stride, string unit, string transducter, string prefiltering, byte isint, double[] minmax, string[] labels)
        {
            this.nsamples = nsamples;
            this.nchannels = nchannels;
            this.stride = stride;
            this.unit = unit;
            this.transducter = transducter;
            this.prefiltering = prefiltering;
            this.isint = isint;
            this.minmax = minmax;
            this.labels = labels;
        }

        public static NeuroDataInfoMsg Deserialize(MessageDeserializer deserializer) => new NeuroDataInfoMsg(deserializer);

        private NeuroDataInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.nsamples);
            deserializer.Read(out this.nchannels);
            deserializer.Read(out this.stride);
            deserializer.Read(out this.unit);
            deserializer.Read(out this.transducter);
            deserializer.Read(out this.prefiltering);
            deserializer.Read(out this.isint);
            deserializer.Read(out this.minmax, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.labels, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.nsamples);
            serializer.Write(this.nchannels);
            serializer.Write(this.stride);
            serializer.Write(this.unit);
            serializer.Write(this.transducter);
            serializer.Write(this.prefiltering);
            serializer.Write(this.isint);
            serializer.WriteLength(this.minmax);
            serializer.Write(this.minmax);
            serializer.WriteLength(this.labels);
            serializer.Write(this.labels);
        }

        public override string ToString()
        {
            return "NeuroDataInfoMsg: " +
            "\nnsamples: " + nsamples.ToString() +
            "\nnchannels: " + nchannels.ToString() +
            "\nstride: " + stride.ToString() +
            "\nunit: " + unit.ToString() +
            "\ntransducter: " + transducter.ToString() +
            "\nprefiltering: " + prefiltering.ToString() +
            "\nisint: " + isint.ToString() +
            "\nminmax: " + System.String.Join(", ", minmax.ToList()) +
            "\nlabels: " + System.String.Join(", ", labels.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
