//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Rosneuro
{
    [Serializable]
    public class NeuroFrameMsg : Message
    {
        public const string k_RosMessageName = "rosneuro_msgs/NeuroFrame";
        public override string RosMessageName => k_RosMessageName;

        //  NeuroFrame Message
        //  Header
        public HeaderMsg header;
        //  NeuroHeader
        public NeuroHeaderMsg neuroheader;
        //  Sampling rate
        public ushort sr;
        //  NeuroData
        public NeuroDataFloatMsg eeg;
        public NeuroDataFloatMsg exg;
        public NeuroDataInt32Msg tri;

        public NeuroFrameMsg()
        {
            this.header = new HeaderMsg();
            this.neuroheader = new NeuroHeaderMsg();
            this.sr = 0;
            this.eeg = new NeuroDataFloatMsg();
            this.exg = new NeuroDataFloatMsg();
            this.tri = new NeuroDataInt32Msg();
        }

        public NeuroFrameMsg(HeaderMsg header, NeuroHeaderMsg neuroheader, ushort sr, NeuroDataFloatMsg eeg, NeuroDataFloatMsg exg, NeuroDataInt32Msg tri)
        {
            this.header = header;
            this.neuroheader = neuroheader;
            this.sr = sr;
            this.eeg = eeg;
            this.exg = exg;
            this.tri = tri;
        }

        public static NeuroFrameMsg Deserialize(MessageDeserializer deserializer) => new NeuroFrameMsg(deserializer);

        private NeuroFrameMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.neuroheader = NeuroHeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.sr);
            this.eeg = NeuroDataFloatMsg.Deserialize(deserializer);
            this.exg = NeuroDataFloatMsg.Deserialize(deserializer);
            this.tri = NeuroDataInt32Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.neuroheader);
            serializer.Write(this.sr);
            serializer.Write(this.eeg);
            serializer.Write(this.exg);
            serializer.Write(this.tri);
        }

        public override string ToString()
        {
            return "NeuroFrameMsg: " +
            "\nheader: " + header.ToString() +
            "\nneuroheader: " + neuroheader.ToString() +
            "\nsr: " + sr.ToString() +
            "\neeg: " + eeg.ToString() +
            "\nexg: " + exg.ToString() +
            "\ntri: " + tri.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
