//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosneuro
{
    [Serializable]
    public class NeuroDataInt32Msg : Message
    {
        public const string k_RosMessageName = "rosneuro_msgs/NeuroDataInt32";
        public override string RosMessageName => k_RosMessageName;

        public NeuroDataInfoMsg info;
        public int[] data;

        public NeuroDataInt32Msg()
        {
            this.info = new NeuroDataInfoMsg();
            this.data = new int[0];
        }

        public NeuroDataInt32Msg(NeuroDataInfoMsg info, int[] data)
        {
            this.info = info;
            this.data = data;
        }

        public static NeuroDataInt32Msg Deserialize(MessageDeserializer deserializer) => new NeuroDataInt32Msg(deserializer);

        private NeuroDataInt32Msg(MessageDeserializer deserializer)
        {
            this.info = NeuroDataInfoMsg.Deserialize(deserializer);
            deserializer.Read(out this.data, sizeof(int), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.info);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "NeuroDataInt32Msg: " +
            "\ninfo: " + info.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
