//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Rosneuro
{
    [Serializable]
    public class NeuroEventMsg : Message
    {
        public const string k_RosMessageName = "rosneuro_msgs/NeuroEvent";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public NeuroHeaderMsg neuroheader;
        public string version;
        public int @event;
        public float duration;
        public int family;
        public string description;

        public NeuroEventMsg()
        {
            this.header = new HeaderMsg();
            this.neuroheader = new NeuroHeaderMsg();
            this.version = "";
            this.@event = 0;
            this.duration = 0.0f;
            this.family = 0;
            this.description = "";
        }

        public NeuroEventMsg(HeaderMsg header, NeuroHeaderMsg neuroheader, string version, int @event, float duration, int family, string description)
        {
            this.header = header;
            this.neuroheader = neuroheader;
            this.version = version;
            this.@event = @event;
            this.duration = duration;
            this.family = family;
            this.description = description;
        }

        public static NeuroEventMsg Deserialize(MessageDeserializer deserializer) => new NeuroEventMsg(deserializer);

        private NeuroEventMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.neuroheader = NeuroHeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.version);
            deserializer.Read(out this.@event);
            deserializer.Read(out this.duration);
            deserializer.Read(out this.family);
            deserializer.Read(out this.description);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.neuroheader);
            serializer.Write(this.version);
            serializer.Write(this.@event);
            serializer.Write(this.duration);
            serializer.Write(this.family);
            serializer.Write(this.description);
        }

        public override string ToString()
        {
            return "NeuroEventMsg: " +
            "\nheader: " + header.ToString() +
            "\nneuroheader: " + neuroheader.ToString() +
            "\nversion: " + version.ToString() +
            "\n@event: " + @event.ToString() +
            "\nduration: " + duration.ToString() +
            "\nfamily: " + family.ToString() +
            "\ndescription: " + description.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
